### ISSUE TITLE
Auto runner compile problem

### ISSUE THREAD

**Issue by jvxgit** [jvxgit/AudYoFlo#20]
When running in automatic build mode in linux, there is an error due to a missing library for openCV:

![grafik](https://github.com/user-attachments/assets/c75b6272-9b03-4c93-94e7-833e95f40191)

Most likely, this bug is due to a wrong library order in the openCV project. I played around with the order until it built when realizing it for the first time.

**Comment by jvxgit** [comment]
It seems that libopenjp2 is not built during openCV compilation as it is already installed in the linux system it runs on.

**Comment by flo-at** [comment]
Now theres also `libprotobuf.a` missing:
```
ninja: error: '/home/runner/work/AudYoFlo/AudYoFlo/sources/jvxLibraries/third_party/git/opencv/opencv/opencv-glnx-Release/lib/opencv4/3rdparty/libprotobuf.a', needed by 'sources/jvxComponents/jvxVideoNodes/jvxViNCameraConvert/libayfViNCameraConvert.so', missing and no known rule to make it
```

**Comment by flo-at** [comment]
Workflow action passes again
